##################################################
# Library Management System
# editor:grand
# date:Dec 23 2016
##################################################
Book:Book.o
	g++ -o Book Book.o

Book.o:Book.cpp 
	g++ -c Book.cpp

clean:
	rm Book Book.o 
